name: aguaconectada
description: "AguaConectada, una aplicación especializada para APRs de todo Chile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1     # Para gestión de estado
  http: ^1.2.0         # Para realizar peticiones HTTP
  shared_preferences: ^2.2.2  # Para almacenamiento local
  intl: ^0.18.1       # Para internacionalización y formateo de fechas
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.5
  fl_chart: ^0.63.0
  firebase_storage: ^11.7.7
  image_picker: ^1.0.7
  badges: ^3.0.2
  excel: ^2.1.0
  camera: ^0.10.5+5
  image: ^4.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Actualizado a la última versión
  mockito: ^5.4.4        # Para pruebas unitarias



flutter:
  uses-material-design: true


#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700